routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/',function(){
	return redirect()->route('home');
});

// * Home *
Route::get('home','Content\HomeController@index')->name('home');

// * Login *
Route::get('login','Auth\LoginController@getLogin')->name('login');
Route::post('login','Auth\LoginController@postLogin')->name('postLogin');

Route::get('login/{social}','Auth\SocialAuthController@redirectToProvider')->name('loginSocial');
Route::get('login/{social}/callback','Auth\SocialAuthController@handleProviderCallback');

// * Logout *
Route::get('logout','Auth\LoginController@logout')->name('logout');

// * Register *
Route::get('register','Auth\RegisterController@getRegister')->name('register');
Route::post('register','Auth\RegisterController@postRegister')->name('postRegister');

// ---------------------- ĐÂY LÀ KHU VỰC ADMIN ----------------------

Route::group(['prefix' => 'admin', 'middleware' => 'admin'],function(){
	Route::get('/',function(){
		return view('admin.dashboard');
	});

	// Category
	Route::resource('categories','Admin\CategoryController');
		//Cập nhật danh mục sản phẩm
		Route::post('categories/{id}','Admin\CategoryController@update')->name('postCategories.update');

	// Product
	Route::resource('products','Admin\ProductController');
		//Cập nhật sản phẩm
		Route::post('products/{id}','Admin\ProductController@update')->name('postProducts.update');

	//Order
	Route::resource('bills','Admin\BillController');

	//Transport
	Route::resource('tranports','Admin\TranportController');
});

//--------------------------------------------------------------------------------------------------------------

//  ------------------- ĐÂY LÀ KHU VỰC CONTENT  -------------------

// * Sản phẩm *
Route::group(['prefix' => 'san-pham'],function(){
	// Chi tiết sản phẩm
	Route::get('{product_slug}','Content\ProductController@showProductDetail')->name('productDetail');
});

// * Giỏ hàng *
Route::group(['prefix' => 'gio-hang'], function(){
	//Hiển thị giỏ hàng
	Route::get('/','Content\CartController@index')->name('cart');

	//Thêm sản phẩm vào giỏ hàng
	Route::post('add','Content\CartController@add')->name('addCart');

	//Xóa sản phẩm trong giỏ hàng
	Route::get('delete','Content\CartController@delete')->name('deleteCart');

	//Xóa *toàn bộ* sản phẩm trong giỏ hàng
	Route::get('destroy','Content\CartController@destroy')->name('destroyCart');

	//Cập nhật sản phẩm trong giỏ hàng
	Route::post('update','Content\CartController@update')->name('updateCart');
});

// * Đặt hàng *
Route::group(['prefix' => 'dat-hang'], function(){
	Route::get('/', 'Content\OrderController@index')->name('getOrder');
	Route::post('/','Content\OrderController@store')->name('postOrder');

	Route::get('load-districts','Content\AreaAjaxController@loadDistricts');
	Route::get('load-wards','Content\AreaAjaxController@loadWards');
	Route::get('load-cul-shipping','Content\OrderController@loadPriceShipping');
});

resources/views/admin/particles/bill.blade.php
@extends('admin.layouts.master')

@section('content')
<section class="content-header">
    <h1>
        Danh sách đơn hàng
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Bill</a></li>
        <li class="active">List</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    @if (Session::has('message'))
    <div class="alert alert-info"> {{ Session::get('message') }}</div>
    @endif
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-md-12">
                    <table id="myTable" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting col-md-1" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="" >Mã đơn hàng</th>
                                <th class="sorting_asc col-md-2" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">Tên khách hàng</th>
                                <th class="sorting col-md-2" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">Ngày đặt hàng</th>
                                {{-- <th class="sorting col-md-1" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">Ngày đặt hàng</th>
                                <th>Email</th> --}}
                                <th>Trạng thái</th>
                                <th class="sorting col-md-1" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">Action</th>
                                <th class="sorting col-md-2" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">Xóa</th></tr>
                            </thead>
                            <tbody>
                                @foreach($bills as $bill)
                                <tr>
                                    <td>#{{ $bill->id }}</td>
                                    <td>{{ $bill->customer_name }}</td>
                                    <td>{{ $bill->bill_date }}</td>

                                    @if($bill->status == 0)
                                        <td>Đang chờ xác nhận</td>
                                    @elseif($bill->status == 1)
                                        <td>Đã xử lý</td>
                                    @elseif($bill->status == 2)
                                        <td>Đang giao hàng</td>
                                    @elseif($bill->status == 3)
                                        <td>Giao hàng thành công</td>
                                    @elseif($bill->status == 4)
                                        <td>Đã hủy</td>
                                    @endif

                                    <td><a href="{{ route('bills.edit',$bill->id) }}">Detail</a></td>
                                    <td>
                                        <form action="{{ route('bills.destroy', $bill->id) }}" method="post" id="formDelete">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <input type="submit" value="Delete" class="btn btn-danger"  onclick="return confirm('Bạn có thực sự muốn xóa?')">
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

resources/views/admin/particles/category.blade.php
@extends('admin.layouts.master');

@section('content')
<section class="content-header">
    <h1>
        Categories
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
        <li><a href="#">Categories</a></li>
        <li class="active">List</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <a href="{{ route('categories.create') }}" class="btn btn-success">
        <i class="fa fa-plus"></i>
        <span>Add Category</span>
    </a>
    <p style="height: 5px"></p>
    @if (Session::has('message'))
        <div class="alert alert-info"> {{ Session::get('message') }}</div>
    @endif
    <input type="text" id="myInput" onkeyup="searchByColumnNo('1')" placeholder="Search for names.." class="form-control">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-sm-12">
                    <table id="myTable" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                        <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">ID</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">Name</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">Slug</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">Parent</th></tr>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label=""></th></tr>
                        </thead>
                        <tbody>

                        @if (isset($listCate) && count($listCate) >0)
                            @foreach($listCate as $cate)
                                <tr role="row" class="odd">
                                    <td>{{ $cate->id }}</td>
                                    <td class="sorting_1">{{ $cate->name }}</td>
                                    <td>{{ $cate->slug }}</td>
                                    <td>
                                        <?php 
                                            $parent = DB::table('categories')->where('id',$cate->parent_id)->first();
                                            if($parent == null){
                                                echo "";
                                            }else{
                                                echo $parent->name;
                                            }
                                        ?>
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <form action="{{ route('categories.destroy', $cate->id) }}" method="post">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}

                                                <a href="{{ url('admin/categories')}}/{{ $cate->id }}/edit" class="btn btn-default bg-purple">
                                                    <i class="fa fa-edit"></i>
                                                    <span>Edits</span>
                                                </a>

                                                <button class="btn btn-default bg-red btnDelete" onclick="return confirm('Bạn có thực sự muốn xóa?')">
                                                    <span>Delete</span>
                                                </button>
                                            </form> 
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                    <div style="float:right">
                        {{-- {!! $listCate->render() !!} --}}
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.box -->

</section>
<!-- /.content -->
<form action="" method="post" id="formDelete">
    <input type="hidden" name="_method" value="DELETE">
    {{ csrf_field() }}
</form>
<div id="confirm" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirm delete</h4>
            </div>
            <div class="modal-body">
                <p> Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">Delete</button>
                <button type="button" data-dismiss="modal" class="btn">Cancel</button>
            </div>
        </div>
    </div>
</div>

@section('page-js-script')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.btnDelete').click(function(){
                var userId = $(this).attr('data-value');
                $('#confirm')
                    .modal({ backdrop: 'static', keyboard: false })
                    .one('click', '#delete', function (e) {
                        //delete function
                        var actionLink = "{{ url('admincp/category')}}/"+ userId;
                        $('#formDelete').attr('action', actionLink).submit();
                    });
            });
        });
    </script>
@endsection
@stop

resources/views/admin/particles/product-create.blade.php
@extends('admin.layouts.master')

@section('content')
  @if(Request::is('*/products/create'))
  	<section class="content-header">
         <h1>
             Thêm sản phẩm
         </h1>
         <ol class="breadcrumb">
             <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
             <li><a href="#">Products</a></li>
             <li class="active">Add</li>
         </ol> 

         @if(Session::has('message'))
          <div class="alert alert-success">{{Session::get('message')}}</div>
         @endif

    </section>
    <section class="content">
           <form action="{{ route('products.store') }}" enctype="multipart/form-data" method="POST">
             <input type="hidden" name='_token' value="{{csrf_token()}}">
             @if(count($errors) >0)
             <ul>
               @foreach($errors->all() as $error)
               <li class="text-danger">{{ $error }}</li>
               @endforeach
             </ul>
             @endif
             <div class="box">
               <div class="box-body row">

                <div class="form-group col-md-12">
                  <label>Tên sản phẩm</label>
                  <input type="text" name="name" class="form-control" value="{{ old('txtName') }}">
                </div>
                <div class="form-group col-md-12">
                  <label>Thông tin sản phẩm</label>
                  <textarea name="description" class="" id="editor1" cols="30" rows="10"></textarea>
                </div>
                <div class="form-group col-md-12">
                  <label>Giá</label>
                  <input type="text" name="price" class="form-control"  value="">
                </div>
                <div class="form-group col-md-12">
                  <label>Giảm giá (%)</label>
                  <input type="text" name="percent_sale" class="form-control"  value="">
                </div>
                <div class="form-group col-md-12">
                  <label>Số lượng</label>
                  <input type="text" name="quantity" class="form-control"  value="">
                </div>
                <div class="form-group col-md-12">
                	<label>Đường dẫn</label>
                	<input type="text" name="slug" class="form-control"  value="">
                </div>
                <div class="form-group col-md-12">
                	<label>Danh mục sản phẩm</label>
                	<select class="form-control" name="category_id"  value="{{ old('parent_id') }}">
                		<option value="0">---</option>
                		@foreach($listCate as $cate)
                		<option value="{{ $cate->id }}">{{ $cate->name }}</option>
                		@endforeach
                	</select>
                </div>
                <div class="form-group col-md-12">
                  <label>Thêm hình ảnh</label>
                  <input type="file" name="upload_images[]" class="form-control"  value="" multiple>
                </div>
                <div class="form-group col-md-12">
                	<fieldset>  <legend>SEO:</legend>
                		Tiêu đề SEO <input type="text" name="meta_title" class="form-control"  value="{{ old('meta_title') }}">
                		Mô tả SEO <input type="text" name="meta_description" class="form-control"  value="{{ old('meta_description') }}">
                	</fieldset>
                </div>
            </div>
            <div class="box-footer row">
            	<button type="submit" class="btn btn-success">
            		<i class="fa fa-save"></i>
            		<span>Lưu và trở lại</span>
            	</button>
            </div>
        </div>
    </form>
    </section>
  @else
    <section class="content-header">
         <h1>
             Cập nhật thông tin sản phẩm
         </h1>
         <ol class="breadcrumb">
             <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
             <li><a href="#">Products</a></li>
             <li class="active">Update</li>
         </ol> 
    </section>
    <section class="content">
           <form action="{{ route('products.update', $product->id) }}" enctype="multipart/form-data" method="POST">
             <input type="hidden" name='_token' value="{{csrf_token()}}">
             @if(count($errors) >0)
             <ul>
               @foreach($errors->all() as $error)
               <li class="text-danger">{{ $error }}</li>
               @endforeach
             </ul>
             @endif
             <div class="box">
               <div class="box-body row">

                <div class="form-group col-md-12">
                  <label>Tên sản phẩm</label>
                  <input type="text" name="name" class="form-control" value="{{ $product->name }}">
                </div>
                <div class="form-group col-md-12">
                  <label>Thông tin sản phẩm</label>
                  <textarea name="description" class="" id="editor1" cols="30" rows="10">{{ $product->description }}</textarea>
                </div>
                <div class="form-group col-md-12">
                  <label>Giá</label>
                  <input type="text" name="price" class="form-control"  value="{{ $product->price }}">
                </div>
                <div class="form-group col-md-12">
                  <label>Giảm giá (%)</label>
                  <input type="text" name="percent_sale" class="form-control"  value="{{ $product->percent_sale }}">
                </div>
                <div class="form-group col-md-12">
                  <label>Số lượng</label>
                  <input type="text" name="quantity" class="form-control"  value="{{ $product->quantity }}">
                </div>
                <div class="form-group col-md-12">
                  <label>Đường dẫn</label>
                  <input type="text" name="slug" class="form-control"  value="{{ $product->slug }}">
                </div>
                <div class="form-group col-md-12">
                  <label>Danh mục sản phẩm</label>
                  <select class="form-control" name="category_id"  value="">
                    <option value="0">---</option>
                    @foreach($categories as $category)
                    <option value="{{ $category->id }}" {{ $category->id == $product->category_id ? 'selected' : "" }} >{{ $category->name }}</option>
                    @endforeach
                  </select>
                </div>
                <div class="form-group col-md-12">
                  <label>Hình ảnh</label>
                  <div id="product_img">
                    @foreach($product_images as $key => $product_image)
                    <div class="product_img" style="width: 150px; float:left; position: relative; margin-right: 20px; margin-bottom: 20px;">
                        <img width="100%" class="img" alt="img_product" name="image_{{ $key + 1 }}" onclick="img_click(event);" src="{{ asset('images/content/products/' . $product_image->name) }}" style="cursor: pointer;">
                        {{-- Cho code them mau sac --}}
                        <a onclick="remove_img(event)" class="btn btn-circle btn-danger" style="width:25px; height: 26px;text-align: center; line-height: 26px; border-radius: 50%; color: white; position: absolute;top: 0; right: 0"><b style="width: 10px; height: 10px;position: absolute;top:-2px;right: 30%;">-</b></a>
                      <input type="file" name="upload_images[]" value="{{ $product_image->name }}" id="image_{{ $key + 1 }}" style="display: none" onchange="preview_img_upload(event,this)">
                      <input type="hidden" name="image_current[]" value="{{ $product_image->name }}">
                    </div>
                    @endforeach
                    <button style="margin-top: 60px;" onclick="add_img(event);" class="btn btn-primary" type="button">Thêm ảnh</button>
                  </div>
                </div>
                <div class="form-group col-md-12">
                  <fieldset>  <legend>SEO:</legend>
                    Tiêu đề SEO <input type="text" name="meta_title" class="form-control"  value="{{ $product->meta_title }}">
                    Mô tả SEO <input type="text" name="meta_description" class="form-control"  value="{{ $product->meta_description }}">
                  </fieldset>
                </div>
            </div>
            <div class="box-footer row">
              <button type="submit" class="btn btn-success">
                <i class="fa fa-save"></i>
                <span>Lưu và trở lại</span>
              </button>

              @if(Session::has('message'))
              <div class="arlert arlert-success">{{Session::get('message')}}</div>
              @endif
            </div>
        </div>
    </form>
    </section>
  @endif
@stop

resources/views/admin/particles/product.blade.php
@extends('admin.layouts.master')

@section('content')
<section class="content-header">
    <h1>
        Products
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
        <li><a href="#">Products</a></li>
        <li class="active">List</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <a href="{{ route('products.create') }}" class="btn btn-success">
        <i class="fa fa-plus"></i>
        <span>Add Product</span>
    </a>
    <p style="height: 5px"></p>
    @if (Session::has('message'))
        <div class="alert alert-info"> {{ Session::get('message') }}</div>
    @endif
    <input type="text" id="myInput" onkeyup="searchByColumnNo('1')" placeholder="Search for names.." class="form-control">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-sm-12">
                    <table id="myTable" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                        <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">ID</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">Name</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">Price</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">Percent_sale</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">Category</th>
                            {{-- <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">Description</th> --}}
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">Slug</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label=""></th>
                        </thead>
                        <tbody>

                        @if (isset($listProduct) && count($listProduct) >0)
                            @foreach($listProduct as $product)
                                <tr role="row" class="odd">
                                    <td>{{ $product->id }}</td>
                                    <td class="sorting_1">{{ $product->name }}</td>
                                    <td>{{ $product->price }}</td>
                                    <td>{{ $product->percent_sale }} %</td>
                                    <td>
                                        <?php 
                                            $category = DB::table('categories')->where('id',$product->category_id)->first();
                                            if($category == null){
                                                echo "Chưa xác định";
                                            }else{
                                                echo $category->name;
                                            }
                                        ?>
                                    </td>
                                    {{-- <td width="300">{{ $product->description }}</td> --}}
                                    <td>{{ $product->slug }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <form action="{{ route('products.destroy', $product->id) }}" method="post">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}

                                                <a href="{{ url('admin/products')}}/{{ $product->id }}/edit" class="btn btn-default bg-purple">
                                                    <i class="fa fa-edit"></i>
                                                    <span>Edits</span>
                                                </a>

                                                <button class="btn btn-default bg-red btnDelete" onclick="return confirm('Bạn có thực sự muốn xóa?')">
                                                    <span>Delete</span>
                                                </button>
                                            </form> 
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                    <div style="float:right">
                        {{-- {!! $listCate->render() !!} --}}
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.box -->

</section>
<!-- /.content -->
<form action="" method="post" id="formDelete">
    <input type="hidden" name="_method" value="DELETE">
    {{ csrf_field() }}
</form>
<div id="confirm" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirm delete</h4>
            </div>
            <div class="modal-body">
                <p> Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">Delete</button>
                <button type="button" data-dismiss="modal" class="btn">Cancel</button>
            </div>
        </div>
    </div>
</div>

@section('page-js-script')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.btnDelete').click(function(){
                var userId = $(this).attr('data-value');
                $('#confirm')
                    .modal({ backdrop: 'static', keyboard: false })
                    .one('click', '#delete', function (e) {
                        //delete function
                        var actionLink = "{{ url('admincp/category')}}/"+ userId;
                        $('#formDelete').attr('action', actionLink).submit();
                    });
            });
        });
    </script>
@endsection
@stop